---
# Main playbook: deploy Patroni cluster nodes, HAProxy and Checkmk (no roles)

- name: DB nodes (PostgreSQL + Patroni)
  hosts: db
  become: true
  gather_facts: true

  handlers:
    - name: Systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart patroni
      ansible.builtin.service:
        name: patroni
        state: restarted

  tasks:
    - name: Include Patroni tasks
      ansible.builtin.import_tasks: tasks/patroni.yaml


- name: HAProxy
  hosts: db
  become: true
  gather_facts: true

  handlers:
    - name: Reload haproxy
      ansible.builtin.service:
        name: haproxy
        state: reloaded

  tasks:
    - name: Include HAProxy tasks
      ansible.builtin.import_tasks: tasks/haproxy.yaml


- name: Monitoring (Checkmk local check)
  hosts: db
  become: true
  gather_facts: true

  tasks:
    - name: Include Checkmk tasks
      ansible.builtin.import_tasks: tasks/checkmk.yaml
