---
# Main playbook: deploy Patroni cluster nodes, HAProxy and Checkmk (no roles)

# etcd (nur wenn etcd_enabled)
- name: etcd (optional)
  hosts: postgreses
  become: true
  gather_facts: true
  tasks:
    - name: Include etcd tasks
      ansible.builtin.import_tasks: tasks/etcd.yaml

- name: DB nodes (PostgreSQL + Patroni)
  hosts: postgreses
  become: true
  gather_facts: true

  handlers:
    - name: Systemd daemon-reload
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Restart patroni
      ansible.builtin.service:
        name: patroni
        state: restarted

  tasks:
    - name: Include Patroni tasks
      ansible.builtin.import_tasks: tasks/patroni.yaml

# keepalived (optional)
- name: keepalived VIP (optional)
  hosts: postgreses
  become: true
  gather_facts: true
  tasks:
    - name: Include keepalived tasks
      ansible.builtin.import_tasks: tasks/keepalived.yaml

- name: HAProxy
  hosts: postgreses
  become: true
  gather_facts: true

  handlers:
    - name: Reload haproxy
      ansible.builtin.service:
        name: haproxy
        state: reloaded

  tasks:
    - name: Include HAProxy tasks
      ansible.builtin.import_tasks: tasks/haproxy.yaml


- name: Monitoring (Checkmk local check)
  hosts: postgreses
  become: true
  gather_facts: true

  tasks:
    - name: Include Checkmk tasks
      ansible.builtin.import_tasks: tasks/checkmk.yaml

